trigger:
- main

pool: 
  name: 'Default'

stages:
- stage: NpmValidation
  jobs:
  - job: NpmValidation
    displayName: Npm Validation
    pool: 'Default'
    steps:
    - checkout: self
      displayName: 'Checkout the repository'
  