trigger:
- main

pool: 
  name: 'Default'

stages:
- stage: NpmValidation
  jobs:
  - job: NpmBasicNonCompliant
    displayName: Npm Build branch 
    pool: 'Default'
    steps:
    - checkout: self
      displayName: 'Checkout the repository'

    - task: nuget-security-analysis@0
      displayName: SSC Task (Staging)
      continueOnError: true
  