trigger:
- main

pool: 
  name: 'Default'

stages:
- stage: NpmValidation
  jobs:
  - job: NpmValidation
    displayName: Npm Validation
    pool: 'Default'
    steps:
    - checkout: self
      displayName: 'Checkout the repository'
    - task: npmAuthenticate@0
      inputs:
        workingFile: '$(Build.SourcesDirectory)/NpmrcNonAA/.npmrc'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)/NpmrcNonAA'
    
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)/BasicNonCompliant'
    
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)/NpmrcNoDefault'
       
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)/NpmrcScopedNonAA'
    
    
    
