trigger:
- main

pool: 
  name: 'Default'

stages:
- stage: NpmValidation
  jobs:
  - job: NpmValidation
    displayName: Npm Validation
    pool: 'Default'
    steps:
    - checkout: self
      displayName: 'Checkout the repository'
    - task: npmAuthenticate@0
      inputs:
        workingFile: '$(Build.SourcesDirectory)/BasicNonCompliant/.npmrc'
 
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)/BasicNonCompliant'
        verbose: true
        
    
    
